---
spring:
  profiles: dev
  application:
    name: config-client-10002
  text: lalalala-dev
--- 
spring:
  profiles: test
  application:
    name: cloud-greenwich-config-client-10002
  text: hahaha-test
